#!/usr/bin/env python3
"""
check41_machinery.py - E2. Verification machinery has not drifted from HEAD.

Why this exists
---------------
`.claude/settings.json` denies Edit and Write on the check directories, and
`.claude/hooks/protect-checks.sh` blocks the same paths for Edit|Write|MultiEdit.
Neither covers **Bash**. `sed -i`, `cat >`, `tee`, `cp`, or a `python3 -c` that
calls `open(..., "w")` all reach `harden/checks/` without either layer seeing
anything, because the hook is registered on the editing tools only.

That gap was recorded as finding 4 of AUDIT-rev7.md and is the reason this file
exists. An executor told to make the board pass can edit the check that grades
it, and every guard in front of that is aimed at a different door.

What this checks, and why it is a detector rather than a preventer
-----------------------------------------------------------------
No PreToolUse hook can be sound against an executor that also holds Bash: the
same command that edits a check can disable the hook, rewrite settings.json, or
set whatever environment variable the hook trusts. Prevention in that setting is
a convenience, not a guarantee.

So the guarantee here is DETECTION, and it is a gate rather than a hook, because
this project's own rule is that a guard which cannot go red is a light. The
board runs it, CI runs the board, and `gate-complete.sh` runs the board before a
session or a subagent may finish. Drift therefore turns something red on the way
out, whatever route produced it.

Baseline is `HEAD`, not a digest snapshot and not MANIFEST.sha256:
  * the manifest is regenerated by `ci/regenerate.sh`, which needs the 323 MB of
    derived data and refuses without it, so it is stale on any data-less clone
    and cannot be the reference here;
  * verifying machinery against a digest file living in the same tree is the
    circularity `data-manifest.json` documents for the data, one level up;
  * `git diff-index HEAD` costs about 4 ms over the 89 protected files and needs
    no state of its own.

"Read-only during a track" therefore means: identical to what was last reviewed
and committed. An authorised change is one a human commits, which git records.

    python3 harden/checks/check41_machinery.py
    python3 harden/checks/check41_machinery.py --list
    python3 harden/checks/check41_machinery.py --is-protected <path>...
    NEGATIVE=1 python3 harden/checks/check41_machinery.py   # must FAIL
"""
import argparse
import fnmatch
import os
import shutil
import subprocess
import sys
import tempfile

_PKG = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

# The single source of truth for what "verification machinery" means. Before
# this file there were two lists - the deny array in settings.json and the case
# statement in protect-checks.sh - and they did not agree: the hook covers
# gates/GATES-*.md and Write() on ci/run_gates.py, the deny list does not.
# Anything added here is covered by the gate AND by guard-machinery.sh, which
# asks this file rather than keeping a third copy.
PROTECTED = [
    "harden/checks/*",
    "retrieval/checks/*",
    "retrieval/checks/superseded/*",
    "pipeline/checks/*",
    "pipeline/checks/superseded/*",
    "pipeline/*/checks/*",
    "verify/*/checks/*",
    "verify/*/checks/superseded/*",
    "gates/GATES-*.md",
    "ci/checks.yaml",
    "ci/run_gates.py",
    "ci/regenerate.sh",
    "ci/test_hooks.sh",
    # The workflow that RUNS the board belongs with the runner it invokes.
    # ci/run_gates.py and ci/checks.yaml were protected and this was not, so an
    # executor could edit or disable CI outright and neither guard-machinery
    # nor this gate would notice. Found while auditing a proposed change to it.
    ".github/workflows/*",
    ".claude/hooks/*",
    ".claude/settings.json",
]

# CI1 writes a deliberately failing check into harden/checks/ and deletes it
# again (ci/run_gates.py, "seed = os.path.join(a.pkg, 'harden', 'checks', ...)").
# It is the control proving the board can go red, so it must not be mistaken for
# tampering during the window it exists.
TRANSIENT = {"harden/checks/check_seeded_failure.py"}


def _candidates(path):
    """Every form of `path` that could name a protected file.

    A guard that matches only repo-relative paths is not a guard. Found by the
    first subagent ever dispatched: `touch /home/user/obc-interactive/harden/
    checks/check35_controls.py` SUCCEEDED from inside a worktree and landed on
    the main checkout, because the absolute form matched no pattern and
    guard-machinery saw an empty hit list. The relative form of the identical
    command was blocked.

    Two forms are therefore tried. First the path relative to this package, for
    the ordinary case. Then every suffix of it, so a path into ANOTHER checkout
    of this repository - the main tree seen from a worktree, or a sibling
    worktree - still matches. Suffix matching can over-match an unrelated file
    that happens to live at `ci/checks.yaml`; refusing that write is the safe
    direction.
    """
    p = path.replace(os.sep, "/")
    out = []
    if os.path.isabs(p):
        try:
            rel = os.path.relpath(p, _PKG).replace(os.sep, "/")
            if not rel.startswith("../"):
                out.append(rel)
        except ValueError:
            pass
        parts = [x for x in p.split("/") if x]
        out += ["/".join(parts[i:]) for i in range(len(parts))]
    else:
        while p.startswith("./"):
            p = p[2:]
        out.append(p)
    return out


def is_protected(rel):
    # NOT lstrip("./"): that strips any leading '.' or '/' CHARACTERS, so
    # ".claude/hooks/decision-guard.sh" became "claude/hooks/..." and silently
    # matched nothing. Every hook file - the most sensitive part of the
    # protected set - was excluded, and the count read 82 instead of 89.
    return any(fnmatch.fnmatch(c, pat) for c in _candidates(rel) for pat in PROTECTED)



def git(args, cwd=_PKG):
    r = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True)
    return r.returncode, r.stdout, r.stderr


def drift(root=_PKG):
    """Return (modified, untracked, error). Empty lists mean no drift."""
    rc, _, err = git(["rev-parse", "--git-dir"], root)
    if rc != 0:
        return [], [], f"not a git working tree ({err.strip()[:80]})"
    # Refresh the index FIRST. `git diff-index` compares stat data and does not
    # refresh, so a file whose mtime or ctime moved while its content stayed
    # identical is reported as modified. ci/test_hooks.sh moves _cmdstrip.py and
    # this file out and back to test the missing-helper cases, which changes
    # ctime; on CI run 11 that alone made E2 report "machinery drifted from
    # HEAD" with nothing whatsoever changed. It passed locally only because an
    # interactive session runs `git status` constantly, which refreshes and
    # rewrites the index as a side effect.
    #
    # A gate that goes red for a reason unrelated to what it guards is this
    # project's own defect in the opposite polarity: not a false green, but a
    # false red, which gets a gate ignored just as thoroughly.
    git(["update-index", "--refresh", "-q"], root)   # non-zero when files differ; not an error
    rc, out, err = git(["diff-index", "--name-only", "HEAD", "--"], root)
    if rc != 0:
        return [], [], f"git diff-index failed ({err.strip()[:80]})"
    modified = [p for p in out.split("\n") if p.strip() and is_protected(p)]
    rc, out, err = git(["ls-files", "--others", "--exclude-standard"], root)
    if rc != 0:
        return modified, [], f"git ls-files failed ({err.strip()[:80]})"
    untracked = [p for p in out.split("\n")
                 if p.strip() and is_protected(p) and p not in TRANSIENT]
    return sorted(modified), sorted(untracked), None


def negative_control():
    """Seed a modification into a copy and require this check to FAIL there.

    The mutation targets the mechanism under test - a protected file - not the
    thing it is scored against, per rule R2.
    """
    src = _PKG
    tmp = tempfile.mkdtemp()
    dst = os.path.join(tmp, "tree")
    try:
        # Exclude the bulky data directories BY PATH, not by name.
        # ignore_patterns("emitters") matches any directory so named, which
        # silently dropped pipeline/emitters/checks/ and verify/emitters/checks/
        # and made the control report eight files as drifted that were not.
        # A control that manufactures its own signal is the defect it exists
        # to catch, one level up.
        heavy = {os.path.join(src, d) for d in ("emitters", "pdf", "model",
                                                os.path.join("verify", "data"))}

        def ignore(directory, names):
            skip = {n for n in names if n in ("__pycache__", "out")}
            if os.path.normpath(directory) in {os.path.normpath(h) for h in
                                               (os.path.dirname(x) for x in heavy)}:
                skip |= {n for n in names if os.path.join(directory, n) in heavy}
            return skip

        shutil.copytree(src, dst, symlinks=True, ignore=ignore)
        victim = os.path.join(dst, "harden", "checks", "check23_controls.py")
        if not os.path.exists(victim):
            print("RESULT: FAIL - control could not run: no check23 to mutate")
            return 1
        with open(victim, "a", encoding="utf-8") as fh:
            fh.write("\n# seeded by check41 negative control\n")
        modified, untracked, err = drift(dst)
        print(f"negative control: mutated harden/checks/check23_controls.py in a copy")
        print(f"  detected modified : {modified}")
        print(f"  error             : {err}")
        if err:
            print("RESULT: FAIL - control could not evaluate the mutated tree")
            return 1
        if "harden/checks/check23_controls.py" not in modified:
            print("RESULT: FAIL - a mutated check went undetected; this gate is void")
            return 1

        # The other half of the control: it must NOT go red for a touch. A gate
        # that fires on mtime is not measuring content, and CI run 11 proved it
        # fires in practice, not just in theory.
        victim2 = os.path.join(dst, "harden", "checks", "check24_metamorphic.py")
        content = open(victim2, "rb").read()
        os.utime(victim2, None)
        modified2, _, err2 = drift(dst)
        open(victim2, "wb").write(content)
        print(f"false-positive control: touched check24 without changing a byte")
        print(f"  reported modified : {'yes - WRONG' if 'harden/checks/check24_metamorphic.py' in modified2 else 'no'}")
        if "harden/checks/check24_metamorphic.py" in modified2:
            print("RESULT: FAIL - the gate reports drift for an unchanged file")
            return 1
        print("RESULT: PASS - detects a real change, ignores a bare touch")
        return 0
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true", help="print every protected file")
    ap.add_argument("--is-protected", nargs="*", metavar="PATH",
                    help="print those of PATH that are protected; used by guard-machinery.sh")
    a = ap.parse_args()

    if a.is_protected is not None:
        # No paths on the command line means read them from stdin, one per line,
        # so guard-machinery.sh can pass a path containing a space safely.
        paths = a.is_protected or [l for l in sys.stdin.read().split("\n") if l.strip()]
        for p in paths:
            if is_protected(p):
                print(p)
        return 0

    if a.list:
        rc, out, _ = git(["ls-files"])
        files = [p for p in out.split("\n") if p.strip() and is_protected(p)]
        for p in sorted(files):
            print(p)
        print(f"{len(files)} protected files")
        return 0

    if os.environ.get("NEGATIVE") == "1":
        return negative_control()

    modified, untracked, err = drift()
    if err:
        print(f"cannot establish the baseline: {err}")
        print("RESULT: FAIL - machinery drift cannot be checked, so it is not checked")
        return 1

    rc, out, _ = git(["ls-files"])
    total = len([p for p in out.split("\n") if p.strip() and is_protected(p)])
    print(f"protected files tracked : {total}")
    print(f"modified vs HEAD        : {len(modified)}")
    print(f"untracked additions     : {len(untracked)}")
    for p in modified:
        print(f"   MODIFIED  {p}")
    for p in untracked:
        print(f"   NEW       {p}")
    if modified or untracked:
        print("\nVerification machinery is read-only during a track (PROTOCOL.md).")
        print("These files differ from the last reviewed commit. Either restore them")
        print("  git checkout -- <path>")
        print("or, if the change is intended, propose it in the audit addendum and let")
        print("a human commit it. An agent that edits the check grading its own work")
        print("has not passed a gate; it has moved one.")
        print("\nRESULT: FAIL - machinery drifted from HEAD")
        return 1
    print("\nRESULT: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
