#!/usr/bin/env python3
"""
check40_dataintegrity.py - the data the gates read is real.

Why this exists
---------------
Every large input is a candidate for arriving empty, truncated, or as a Git LFS
pointer stub. Claude Code's cloud sandbox proxy rejects the LFS batch endpoint
(anthropics/claude-code#25043, recurring as #60593), so an LFS-tracked 70 MB
database clones as a ~130-byte text file beginning:

    version https://git-lfs.github.com/spec/v1

A gate that opens that file does not crash. `sqlite3.connect` on a text file
succeeds; the first query fails, or worse, a checker that counts rows reports
zero and a ratio computed over zero denominators reports 100%. That is the
silent-wrong-data failure this project has found six times in other forms.

This runs FIRST, before any gate that reads data, and fails closed.

Reference: data-manifest.json, which is an input - not regenerated by
ci/regenerate.sh. Verifying data against a manifest derived from the same tree
would be circular, which is check33's error in a new place.

    python3 harden/checks/check40_dataintegrity.py
    python3 harden/checks/check40_dataintegrity.py --quick   # size + stub only
"""
import argparse, hashlib, json, os, sys

_PKG = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
LFS_MAGIC = b"version https://git-lfs.github.com/spec/v1"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default=os.path.join(_PKG, "data-manifest.json"))
    ap.add_argument("--quick", action="store_true", help="skip sha256 (size + stub only)")
    a = ap.parse_args()

    if not os.path.exists(a.manifest):
        print(f"RESULT: FAIL - no data manifest at {a.manifest}"); sys.exit(1)
    man = json.load(open(a.manifest))
    missing, stubs, wrong_size, wrong_hash = [], [], [], []

    for r in man["files"]:
        p = os.path.join(_PKG, r["path"])
        if not os.path.exists(p):
            missing.append(r["path"]); continue
        n = os.path.getsize(p)
        # a pointer stub is small and starts with the LFS magic
        if n < 1024:
            head = open(p, "rb").read(64)
            if head.startswith(LFS_MAGIC):
                stubs.append(r["path"]); continue
        if n != r["bytes"]:
            wrong_size.append(f"{r['path']} ({n} != {r['bytes']})"); continue
        if not a.quick:
            h = hashlib.sha256()
            with open(p, "rb") as fh:
                for chunk in iter(lambda: fh.read(1 << 20), b""):
                    h.update(chunk)
            if h.hexdigest() != r["sha256"]:
                wrong_hash.append(r["path"])

    # Coverage: every path git excludes as data must be restorable from the
    # manifest, or a fresh clone is silently short a file. Found the hard way -
    # .gitignore excluded verify/data/**/*.json, the manifest listed only the
    # .gz files, and labels.json vanished from a fresh clone. H4's control_toc
    # failed 40 minutes later with a message about a TOC target, not a missing
    # file. A gap between what is removed and what is restored must be a gate,
    # not a thing someone remembers to keep in sync.
    import fnmatch
    pats = [l.strip() for l in open(os.path.join(_PKG, ".gitignore"))
            if l.strip() and not l.startswith("#")]
    data_pats = [p for p in pats if any(p.startswith(d) for d in ("pdf/", "emitters/", "model/", "verify/data/"))]
    declared = {r["path"] for r in man["files"]}
    allowed = set(man.get("intentionally_absent") or [])
    gap = []
    for root, dirs, files in os.walk(_PKG):
        dirs[:] = [d for d in dirs if d not in (".git", "__pycache__", "out")]
        for f in files:
            rel = os.path.relpath(os.path.join(root, f), _PKG)
            for pat in data_pats:
                base = pat.replace("**/", "")
                if fnmatch.fnmatch(rel, pat) or fnmatch.fnmatch(rel, base):
                    if rel not in declared and rel not in allowed:
                        gap.append(rel)
                    break
    if gap:
        print(f"GITIGNORED BUT NOT IN THE MANIFEST: {len(gap)}")
        for x in sorted(gap)[:5]:
            print(f"   {x}   (a fresh clone would not have this file)")

    ok = len(man["files"]) - len(missing) - len(stubs) - len(wrong_size) - len(wrong_hash)
    print(f"data files declared : {len(man['files'])} ({man['total_bytes']/1048576:.0f} MB)")
    print(f"verified            : {ok}" + ("  (size + stub only; --quick)" if a.quick else "  (size + sha256)"))
    for label, items in (("MISSING", missing), ("LFS POINTER STUBS", stubs),
                         ("WRONG SIZE", wrong_size), ("WRONG SHA256", wrong_hash)):
        if items:
            print(f"{label:<20}: {len(items)}")
            for x in items[:4]: print(f"   {x}")
    if stubs:
        print("\n   LFS pointer stubs mean the clone did not fetch the objects. Run"
              "\n   `git lfs pull`, or `bash ci/fetch_data.sh` if data lives in a release."
              "\n   Claude Code's cloud sandbox cannot fetch LFS at all (claude-code#25043):"
              "\n   use local CLI or a devcontainer for any session that runs gates.")
    fails = missing or stubs or wrong_size or wrong_hash or gap
    print("\nRESULT:", "PASS" if not fails else "FAIL - the gates would read wrong data")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
